'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Aluno
    Public Property AlunoId As Integer
    Public Property AlunoNome As String
    Public Property DepartamentoID As Nullable(Of Integer)
    Public Property AssuntoID As Nullable(Of Integer)

    Public Overridable Property Assunto As Assunto
    Public Overridable Property Departamento As Departamento

End Class
